/obj/item/ego_weapon/shield/officer/records
	name = "部长军刀"
	desc = "一把古老的军刀，也可用作拐杖，由记录部长使用. "
	special = "这把武器拿在手中即可提供额外的速度加成."
	force = 2
	attack_speed = 0.5
	damtype = WHITE_DAMAGE
	attack_verb_continuous = list("stabs", "attacks", "slashes")
	attack_verb_simple = list("stab", "attack", "slash")
	hitsound = 'sound/weapons/ego/rapier1.ogg'
	level_to_force = list(2, 4, 6, 9, 14)//Meant to be overall bad for dps since its both a parry weapon and a speed boost
	initial_reductions = list(20,10,10,0)
	projectile_block_duration = 0.75 SECONDS
	block_duration = 1.25 SECONDS
	block_cooldown = 3 SECONDS
	block_message = "你尝试格挡攻击!"
	hit_message = "格挡攻击!"
	block_cooldown_message = "你重整了刀刃."
	slowdown = -0.3//its a walking cane
	item_flags = SLOWS_WHILE_IN_HAND
	allowed_roles = list("Records Officer")
	extra_text = "这把武器只能由记录部长使用. 这把武器在击败的考验越多时，力量也会随之增强."
